spin_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = "Social media app for code snippets"
name = "code-things"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
db_user = { default = "code-things" }
db_pswd = { default = "password" }
db_host = { default = "127.0.0.1" }
db_name = { default = "code_things" }
auth_domain = { default = "dev-czhnnl8ikcojc040.us.auth0.com" }
auth_audience = { default = "https://code-things.fermyon.app/api" }
auth_max_validity_secs = { default = "86400" }

[[component]]
id = "web"
source = "modules/spin_static_fs.wasm"
environment = { FALLBACK_PATH = "index.html" }
[[component.files]]
source = "web/dist"
destination = "/"
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "web"

[[component]]
id = "profile-api"
source = "api/profile/target/wasm32-wasi/release/profile_api.wasm"
allowed_http_hosts = [ "dev-czhnnl8ikcojc040.us.auth0.com" ]
[component.trigger]
route = "/api/profile/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api/profile"
watch = ["api/profile/src/**/*.rs", "api/profile/Cargo.toml", "spin.toml"]
[component.config]
db_url = "host={{db_host}} user={{db_user}} password={{db_pswd}} dbname={{db_name}}"
auth_domain = "{{ auth_domain }}"
auth_audience = "{{ auth_audience }}"
auth_max_validity_secs = "{{ auth_max_validity_secs }}"

[[component]]
id = "post"
source = "./api/post/main.wasm"
allowed_http_hosts = [ "dev-czhnnl8ikcojc040.us.auth0.com" ]
[component.trigger]
route = "/api/post/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm ."
workdir = "./api/post"
watch = ["api/post/*.go", "api/post/go.mod", "spin.toml"]
[component.config]
db_url = "host={{db_host}} user={{db_user}} password={{db_pswd}} dbname={{db_name}}"
auth_domain = "{{ auth_domain }}"
auth_audience = "{{ auth_audience }}"
