name: Deploy

on:
  push:
    branches:
    - main
    - feature/deploy-to-cloud
  workflow_dispatch:

jobs:
  spin:
    runs-on: ubuntu-22.04
    name: Build application
    steps:
      - uses: actions/checkout@v3

      - name: Setup `rust`
        uses: dtolnay/rust-toolchain@stable
        with:
            targets: wasm32-wasi
            components: clippy, rustfmt

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: 'api/post/go.mod'
          cache-dependency-path: 'api/post/go.sum'

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "canary"

      # this won't be necessary once v0.28 of tinygo is released
      - name: Setup `tinygo`
        run: |
          echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install clang-15 llvm-15-dev lld-15 libclang-15-dev
          go install github.com/tinygo-org/tinygo@dev

      - name: Show Versions
        run: |
          rustup show
          echo "----------------------------"
          go version
          tinygo version
          echo "----------------------------"
          spin --version

      - name: Build & Deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
